# Generated by Django 4.2.30 on 2026-05-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MuscleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('calories', models.IntegerField(verbose_name='Калорії')),
                ('protein', models.IntegerField(verbose_name='Білки')),
                ('description', models.TextField(verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('difficulty', models.CharField(max_length=50, verbose_name='Складність')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено о')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено о')),
                ('muscle_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='gym.musclegroup', verbose_name="Група м'язів")),
            ],
        ),
    ]
