# Generated by Django 4.2.30 on 2026-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Фото'),
        ),
    ]
