# Generated by Django 4.2.29 on 2026-05-14 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_newslettersubscriber_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Посилання на фото'),
        ),
    ]
